const rows = [
  { eventName: "Cloud Innovation Summit", date: "2024-10-15", speaker: 'Jane Doe', status: "completed" },
  { eventName: "BlockChain Revolution Conference", date: "2024-11-05", speaker: 'Dr Peter Smith', status: "in progress" },
  { eventName: "AI in Healthcare Symposium", date: "2024-12-01", speaker: 'Dr Aisha Malik', status: "completed" },
  { eventName: "Future of Fintech Forum", date: "2024-10-25", speaker: 'John Lee', status: "completed" },
  { eventName: "Data Analytics in Business", date: "2024-11-12", speaker: 'Rachel Moore', status: "completed" },
  { eventName: "Sustainable Energy Expo", date: "2024-09-28", speaker: 'Prof. Alan Green', status: "completed" },
  { eventName: "Web3 Interface workshop", date: "2024-10-10", speaker: 'Kevin Adams', status: "in progress" },
  { eventName: "Cybersecurity for Startups", date: "2024-11-19", speaker: 'Emily Zhange', status: "completed" },
  { eventName: "Smart Cities Forum", date: "2024-10-18", speaker: 'Dr. Maria Hernandex', status: "in progress" },
  { eventName: "Tech Safari Mixer", date: "2024-09-30", speaker: 'Guest Panel', status: "in progress" },
  { eventName: "Quantum Computing Conference", date: "2024-11-15", speaker: 'Dr. Lucy Wang', status: "in progress" },
  { eventName: "IoT Innovations Expo", date: "2024-12-10", speaker: 'Samantha Lee', status: "completed" },
  { eventName: "5G and Beyond Symposium", date: "2024-12-02", speaker: 'Prof. Derek White', status: "completed" },
  { eventName: "Virtual Reality Summit", date: "2024-11-22", speaker: 'James Carter', status: "in progress" },
  { eventName: "Agile Transformation Workshop", date: "2024-10-29", speaker: 'Lisa Roberts', status: "completed" },
  { eventName: "Green Tech Expo", date: "2024-09-25", speaker: 'Dr. Karen Davis', status: "completed" },
  { eventName: "AI for Education Forum", date: "2024-12-15", speaker: 'Dr. Michael Evans', status: "completed" },
  { eventName: "Cloud Security Summit", date: "2024-11-01", speaker: 'David Kim', status: "completed" },
  { eventName: "Blockchain for Finance Symposium", date: "2024-10-14", speaker: 'Dr. Steven Morris', status: "completed" },
  { eventName: "Augmented Reality in Retail Conference", date: "2024-11-28", speaker: 'Julia Clarke', status: "in progress" },
  { eventName: "DevOps World Congress", date: "2024-10-03", speaker: 'Ryan Anderson', status: "completed" },
  { eventName: "AI and Robotics Expo", date: "2024-12-08", speaker: 'Natalie Scott', status: "completed" },
  { eventName: "Tech Leadership Forum", date: "2024-11-10", speaker: 'Tom Richards', status: "in progress" },
  { eventName: "Data Privacy Symposium", date: "2024-11-29", speaker: 'Emma Watson', status: "completed" },
  { eventName: "Innovations in Healthcare AI", date: "2024-10-20", speaker: 'Dr. Andrew Brown', status: "completed" },
  { eventName: "Autonomous Vehicles Expo", date: "2024-09-20", speaker: 'Chris Martinez', status: "completed" },
  { eventName: "Digital Twins in Industry Forum", date: "2024-12-05", speaker: 'Dr. Philip Davis', status: "in progress" },
  { eventName: "Smart Manufacturing Summit", date: "2024-11-17", speaker: 'Sophia Turner', status: "completed" },
  { eventName: "AI and Ethics Symposium", date: "2024-10-06", speaker: 'Dr. Jessica Parker', status: "completed" },
  { eventName: "Fintech and AI Workshop", date: "2024-11-25", speaker: 'Matthew Hill', status: "in progress" }
];

export { rows };
